version : '3.5'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - production-network
  mysqlhost:
    build:
      dockerfile: ./docker/mysql.dockerfile
      context: .
    image: gabrielsmartins/mysql
    container_name: mysql
    ports:
      - "12345:3306"
    #restart: always
    networks:
      - production-network
  app1:
    build:
      dockerfile: ./docker/smart-payment-credit-card.dockerfile
      context: .
    image: gabrielsmartins/smart-payment-credit-card
    container_name: smart-payment-credit-card1
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2
    networks:
      - production-network
    depends_on:
      - "mysqlhost"
  app2:
    build:
      dockerfile: ./docker/smart-payment-credit-card.dockerfile
      context: .
    image: gabrielsmartins/smart-payment-credit-card
    container_name: smart-payment-credit-card2
    ports:
      - "8081:8080"
    volumes:
      - ~/.m2:/root/.m2
    networks:
      - production-network
    depends_on:
      - "mysqlhost"
  app3:
    build:
      dockerfile: ./docker/smart-payment-credit-card.dockerfile
      context: .
    image: gabrielsmartins/smart-payment-credit-card
    container_name: smart-payment-credit-card3
    ports:
      - "8082:8080"
    volumes:
      - ~/.m2:/root/.m2
    networks:
      - production-network
    depends_on:
      - "mysqlhost"
networks:
  production-network:
    driver: bridge
