server:
  port: 8080
  
info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  #boot:
    #admin:
      #client:
        #url: http://localhost:8081
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlhost:3306/creditcarddb?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 12345
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
  main:
    allow-bean-definition-overriding : true
    
#eureka:
  #client:
   # fetch-registry: false
    #register-with-eureka: false
    #service-url:
      #defaultZone : http://localhost:8761/eureka


